import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";

import NextAuthSessionProvider from "@/Providers/authProvider/NextAuthSessionProvider";
import type { Metadata } from "next";
import NavbarFooterWrapper from "@/Providers/authProvider/NavbarFooterWrapper";

export const metadata: Metadata = {
  title: "Tour Management System",
  description: "Generated by Tour Management System",
  icons: {
    icon: "https://i.ibb.co.com/B53BH7vQ/icon.png",
    shortcut: "https://i.ibb.co.com/B53BH7vQ/icon.png",
    apple: "https://i.ibb.co.com/B53BH7vQ/icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <NextAuthSessionProvider>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavbarFooterWrapper>
              <Toaster position="top-right" reverseOrder={false} />

              {children}
            </NavbarFooterWrapper>
          </ThemeProvider>
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
