import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";

import NextAuthSessionProvider from "@/Providers/authProvider/NextAuthSessionProvider";

import NavbarFooterWrapper from "@/Providers/authProvider/NavbarFooterWrapper";

export const metadata = {
  title: "Tour Management System",
  description: "Generated by Tour Management System",
  icons: {
    icon: "/iconLogo.png",       // default favicon
    apple: "/iconLogo.png",      // apple touch icon
    shortcut: "/iconLogo.png",   // shortcut icon
  },
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
     

      <NextAuthSessionProvider>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavbarFooterWrapper>
              <Toaster position="top-right" reverseOrder={false} />

              {children}
            </NavbarFooterWrapper>
          </ThemeProvider>
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
